import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

test('server-renders bounded homepage marketplace data without exposing owner identity', () => {
  const home = readFileSync(new URL('../src/components/views/home-view.tsx', import.meta.url), 'utf8')
  const page = readFileSync(new URL('../src/app/page.tsx', import.meta.url), 'utf8')
  const layout = readFileSync(new URL('../src/app/layout.tsx', import.meta.url), 'utf8')

  assert.doesNotMatch(home, /^['"]use client['"]/)
  assert.match(home, /db\.part\.findMany/)
  assert.match(home, /db\.store\.findMany/)
  assert.match(home, /take: 16/)
  assert.match(home, /take: 12/)
  assert.doesNotMatch(home, /fetch\(['"]\/api\/(?:parts|stores)/)
  assert.doesNotMatch(home, /owner:\s*\{\s*select/)
  assert.match(home, /import Form from 'next\/form'/)
  assert.match(home, /<Form action="\/parts"/)
  assert.match(page, /<HomeView\s*\/>/)
  assert.match(page, /export const revalidate = 30/)
  assert.doesNotMatch(layout, /متاجر موثوقة/)
})

test('server-renders product and store details through privacy-safe public loaders', () => {
  const routes = readFileSync(new URL('../src/app/[...route]/page.tsx', import.meta.url), 'utf8')
  const publicData = readFileSync(new URL('../src/lib/public-marketplace.ts', import.meta.url), 'utf8')
  const partView = readFileSync(new URL('../src/components/views/part-view.tsx', import.meta.url), 'utf8')
  const storeView = readFileSync(new URL('../src/components/views/store-view.tsx', import.meta.url), 'utf8')

  assert.match(routes, /initialPart=\{part\}/)
  assert.match(routes, /initialStore=\{store\}/)
  assert.match(routes, /if \(!part\) notFound\(\)/)
  assert.match(routes, /if \(!store\) notFound\(\)/)
  assert.match(publicData, /isOwnedByViewer:/)
  assert.match(publicData, /items: \{ some: \{ partId \} \}/)
  assert.doesNotMatch(partView, /part\.store\.owner/)
  assert.doesNotMatch(storeView, /store\.owner/)
  assert.doesNotMatch(storeView, /quality=\{100\}/)
  assert.match(storeView, /store\.verified &&/)
})

test('server-renders bounded marketplace lists without seller profile data', () => {
  const routes = readFileSync(new URL('../src/app/[...route]/page.tsx', import.meta.url), 'utf8')
  const publicData = readFileSync(new URL('../src/lib/public-marketplace.ts', import.meta.url), 'utf8')
  const partsApi = readFileSync(new URL('../src/app/api/parts/route.ts', import.meta.url), 'utf8')
  const storesApi = readFileSync(new URL('../src/app/api/stores/route.ts', import.meta.url), 'utf8')
  const partsView = readFileSync(new URL('../src/components/views/parts-view.tsx', import.meta.url), 'utf8')
  const storesView = readFileSync(new URL('../src/components/views/stores-view.tsx', import.meta.url), 'utf8')

  assert.match(routes, /getPublicPartsList\(initialQuery\)/)
  assert.match(routes, /<PartsView initialData=\{initialData\}/)
  assert.match(routes, /getPublicStoresList\(search, initialPage\)/)
  assert.match(routes, /<StoresView initialData=\{initialData\}/)
  assert.match(publicData, /const pageSize = 24/)
  assert.match(publicData, /const pageSize = 18/)
  assert.match(publicData, /take: pageSize/)
  assert.match(publicData, /completionRate: decided \?/)
  assert.match(partsApi, /getPublicPartsList/)
  assert.match(storesApi, /getPublicStoresList/)
  assert.doesNotMatch(partsView, /part\.store\.owner/)
  assert.doesNotMatch(storesView, /store\.owner/)
  assert.doesNotMatch(partsView, /quality=\{100\}/)
  assert.doesNotMatch(storesView, /quality=\{100\}/)
  assert.doesNotMatch(storesView, /completionRate \?\? 100/)
})

test('keeps marketplace navigation and controls accessible', () => {
  const partsView = readFileSync(new URL('../src/components/views/parts-view.tsx', import.meta.url), 'utf8')
  const storesView = readFileSync(new URL('../src/components/views/stores-view.tsx', import.meta.url), 'utf8')
  const partView = readFileSync(new URL('../src/components/views/part-view.tsx', import.meta.url), 'utf8')
  const checkout = readFileSync(new URL('../src/components/views/checkout-view.tsx', import.meta.url), 'utf8')
  const dispute = readFileSync(new URL('../src/components/dispute-dialog.tsx', import.meta.url), 'utf8')

  assert.match(partsView, /aria-label="البحث في قطع الغيار"/)
  assert.match(partsView, /aria-label="تصفية حسب الفئة"/)
  assert.match(partsView, /aria-label="ترتيب قطع الغيار"/)
  assert.match(storesView, /aria-label="البحث عن متجر"/)
  assert.doesNotMatch(partsView, /role="link"/)
  assert.doesNotMatch(storesView, /role="link"/)
  assert.match(partView, /<h2[^>]*>الوصف<\/h2>/)
  assert.match(partView, /السيارات المتوافقة[\s\S]*<\/h2>/)
  assert.match(checkout, /<SelectTrigger aria-label="اختيار المحافظة"/)
  assert.match(dispute, /aria-label="نوع طلب الحماية"/)
})

test('keeps public SSR routes independent from session resolution', () => {
  const homePage = readFileSync(new URL('../src/app/page.tsx', import.meta.url), 'utf8')
  const routes = readFileSync(new URL('../src/app/[...route]/page.tsx', import.meta.url), 'utf8')
  const shell = readFileSync(new URL('../src/components/app-shell.tsx', import.meta.url), 'utf8')
  assert.doesNotMatch(homePage, /getSession/)
  assert.match(routes, /const user = null/)
  assert.doesNotMatch(routes, /await getSession\(\)/)
  assert.match(shell, /\/api\/auth\/me/)
  assert.match(shell, /Public SSR remains identity-free/)
})

test('keeps the shared shell persistent and navigation URL-driven', () => {
  const layout = readFileSync(new URL('../src/app/layout.tsx', import.meta.url), 'utf8')
  const shell = readFileSync(new URL('../src/components/app-shell.tsx', import.meta.url), 'utf8')
  const store = readFileSync(new URL('../src/lib/store.ts', import.meta.url), 'utf8')
  const header = readFileSync(new URL('../src/components/header.tsx', import.meta.url), 'utf8')
  const mobileNav = readFileSync(new URL('../src/components/mobile-bottom-nav.tsx', import.meta.url), 'utf8')
  const cart = readFileSync(new URL('../src/components/cart-drawer.tsx', import.meta.url), 'utf8')
  const admin = readFileSync(new URL('../src/components/views/admin-dashboard-view.tsx', import.meta.url), 'utf8')
  const wishlistApi = readFileSync(new URL('../src/app/api/wishlist/route.ts', import.meta.url), 'utf8')
  const favoriteButton = readFileSync(new URL('../src/components/favorite-store-button.tsx', import.meta.url), 'utf8')
  const wishlist = readFileSync(new URL('../src/components/views/wishlist-view.tsx', import.meta.url), 'utf8')

  assert.match(layout, /<AppShell>\{children\}<\/AppShell>/)
  assert.match(shell, /usePathname\(\)/)
  assert.match(shell, /fetch\('\/api\/auth\/me'/)
  assert.doesNotMatch(shell, /initialView|setAppNavigator|window\.location\.assign/)
  assert.doesNotMatch(store, /setView|setAppNavigator|searchQuery:/)
  assert.match(header, /usePathname\(\)/)
  assert.match(header, /<Link href="\/parts"/)
  assert.match(header, /max-xl:order-last/)
  assert.match(mobileNav, /usePathname\(\)/)
  assert.doesNotMatch(mobileNav, /LifeBuoy|href: '\/support'/)
  assert.match(mobileNav, /grid-cols-5/)
  assert.match(cart, /useAppNavigation/)
  assert.doesNotMatch(header, /setView|view\.name/)
  assert.doesNotMatch(mobileNav, /view\.name/)
  assert.match(admin, /usePathname\(\)/)
  assert.match(admin, /router\.push\(`\/admin\/\$\{v\}`\)/)
  assert.doesNotMatch(admin, /window\.history\.pushState/)
  assert.match(shell, /if \(pathname === '\/account\/wishlist'\) return \['BUYER', 'SHOP_OWNER', 'ADMIN'\]/)
  assert.match(wishlistApi, /requireRoles\(\['BUYER', 'SHOP_OWNER', 'ADMIN'\]\)/)
  assert.match(favoriteButton, /user\?\.role === 'ADMIN'/)
  assert.match(wishlist, /\['BUYER', 'SHOP_OWNER', 'ADMIN'\]/)
})

test('loads seller tabs independently and scopes support cache by user and filters', () => {
  const seller = readFileSync(new URL('../src/components/views/shop-dashboard-view.tsx', import.meta.url), 'utf8')
  const sellerCache = readFileSync(new URL('../src/lib/seller-dashboard-cache.ts', import.meta.url), 'utf8')
  const warmup = readFileSync(new URL('../src/lib/dashboard-warmup.ts', import.meta.url), 'utf8')
  const support = readFileSync(new URL('../src/components/views/support-view.tsx', import.meta.url), 'utf8')

  assert.match(sellerCache, /tab === 'parts' \? '\/api\/parts\?scope=mine'/)
  assert.match(sellerCache, /tab === 'orders' \? '\/api\/orders\?scope=shop'/)
  assert.match(sellerCache, /'\/api\/shop\/store'/)
  assert.match(warmup, /warmSellerAnalytics/)
  assert.match(warmup, /warmSellerCoupons/)
  assert.match(warmup, /warmSellerMessages/)
  assert.match(seller, /loadSellerCore/)
  assert.doesNotMatch(seller, /Promise\.all\(\[\s*fetch\('\/api\/shop\/store'/)
  assert.match(support, /supportCacheKey\(user\.id, user\.role, statusFilter, categoryFilter, ticketSearch\)/)
  assert.match(support, /SUPPORT_CACHE_TTL/)
  assert.match(support, /supportCache\.clear\(\)/)
})

test('expands structured fitment additively and warns before checkout', () => {
  const schema = readFileSync(new URL('../prisma/schema.prisma', import.meta.url), 'utf8')
  const migration = readFileSync(new URL('../prisma/structured-fitment.sql', import.meta.url), 'utf8')
  const publicData = readFileSync(new URL('../src/lib/public-marketplace.ts', import.meta.url), 'utf8')
  const checkout = readFileSync(new URL('../src/components/views/checkout-view.tsx', import.meta.url), 'utf8')

  assert.match(schema, /universal\s+Boolean\s+@default\(false\)/)
  assert.match(schema, /generation\s+String\?/)
  assert.match(schema, /trim\s+String\?/)
  assert.match(migration, /add column if not exists "universal"/)
  assert.doesNotMatch(migration, /\b(?:drop|truncate|delete)\b/i)
  assert.match(publicData, /compatibilities:\s*\{\s*select/)
  assert.doesNotMatch(publicData, /userCar|selectedCar|carId/)
  assert.match(publicData, /universal: true/)
  assert.match(checkout, /راجع توافق القطع قبل تأكيد الطلب/)
})

test('keeps typo-tolerant marketplace search indexed and bounded', () => {
  const migration = readFileSync(new URL('../prisma/search-tolerance.sql', import.meta.url), 'utf8')
  const search = readFileSync(new URL('../src/lib/marketplace-search.ts', import.meta.url), 'utf8')

  assert.match(migration, /VehicleCompatibility_search_trgm_idx/)
  assert.match(migration, /Store_search_trgm_idx/)
  assert.doesNotMatch(migration, /\b(?:drop|truncate|delete)\b/i)
  assert.match(search, /operator\(extensions\.%>\)/)
  assert.match(search, /Math\.min\(Math\.max\(limit, 1\), 500\)/)
})

test('keeps grouped-order reviews authorized and trust claims evidence based', () => {
  const reviewsRoute = readFileSync(new URL('../src/app/api/reviews/route.ts', import.meta.url), 'utf8')
  const publicData = readFileSync(new URL('../src/lib/public-marketplace.ts', import.meta.url), 'utf8')
  const partView = readFileSync(new URL('../src/components/views/part-view.tsx', import.meta.url), 'utf8')

  assert.match(reviewsRoute, /items:\s*\{\s*some:\s*\{\s*partId:\s*targetId/)
  assert.match(publicData, /qualifyingReviewKeys/)
  assert.match(publicData, /status: \{ in: \['DELIVERED', 'RETURNED'\] \}/)
  assert.match(publicData, /take: 50/)
  assert.match(partView, /شراء موثق/)
  assert.doesNotMatch(partView, /توصيل سريع|إمكانية الاسترجاع/)
})

test('bounds store detail inventory and reviews while preserving aggregate totals', () => {
  const publicData = readFileSync(new URL('../src/lib/public-marketplace.ts', import.meta.url), 'utf8')
  const storeView = readFileSync(new URL('../src/components/views/store-view.tsx', import.meta.url), 'utf8')

  assert.match(publicData, /parts:\s*\{[\s\S]*?take:\s*24/)
  assert.match(publicData, /reviews:\s*\{[\s\S]*?take:\s*20/)
  assert.match(publicData, /storeReview\.findMany/)
  assert.match(publicData, /isDevelopmentReviewAuthor/)
  assert.match(storeView, /\/parts\?storeId=/)
  assert.match(storeView, /store\.partCount/)
})

test('requires a normalized delivery phone on both checkout paths', () => {
  const orders = readFileSync(new URL('../src/app/api/orders/route.ts', import.meta.url), 'utf8')
  const checkout = readFileSync(new URL('../src/components/views/checkout-view.tsx', import.meta.url), 'utf8')
  const partView = readFileSync(new URL('../src/components/views/part-view.tsx', import.meta.url), 'utf8')

  assert.match(orders, /normalizeEgyptianMobile\(session\.phone\)/)
  assert.match(checkout, /hasDeliveryPhone/)
  assert.match(partView, /hasDeliveryPhone/)
})

test('requires positive product prices at every seller write boundary', () => {
  const partsApi = readFileSync(new URL('../src/app/api/parts/route.ts', import.meta.url), 'utf8')
  const aiActions = readFileSync(new URL('../src/lib/ai/actions.ts', import.meta.url), 'utf8')
  const sellerView = readFileSync(new URL('../src/components/views/shop-dashboard-view.tsx', import.meta.url), 'utf8')
  const migration = readFileSync(new URL('../prisma/positive-part-prices.sql', import.meta.url), 'utf8')

  assert.match(partsApi, /numericPrice <= 0/)
  assert.match(partsApi, /يجب أن يكون سعر المنتج أكبر من صفر/)
  assert.match(aiActions, /input\.price > 0/)
  assert.match(sellerView, /min="0\.01"/)
  assert.match(migration, /check \("price" > 0\)/i)
  assert.doesNotMatch(migration, /\b(?:delete|drop|truncate)\b/i)
})

test('keeps JSON and CSV inventory mutations positive-price and atomic', () => {
  const inventory = readFileSync(new URL('../src/app/api/shop/inventory/route.ts', import.meta.url), 'utf8')
  assert.match(inventory, /price <= 0/)
  assert.match(inventory, /parseCsv/)
  assert.match(inventory, /preview/)
  assert.match(inventory, /storeId, id: \{ in:/)
  assert.match(inventory, /updateMany\(\{\s*where:\s*\{\s*id: item\.id,\s*storeId\s*\}/)
  assert.match(inventory, /لم يتم حفظ أي صف/)
})

test('keeps the service worker privacy-safe and removes the obsolete socket path', () => {
  const serviceWorker = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
  const notifications = readFileSync(new URL('../src/components/notifications-bell.tsx', import.meta.url), 'utf8')
  const config = readFileSync(new URL('../next.config.ts', import.meta.url), 'utf8')
  const legacyService = new URL('../mini-services/notifications/index.ts', import.meta.url)

  assert.match(serviceWorker, /ghyar-market-static-v3/)
  assert.match(serviceWorker, /STATIC_ASSETS/)
  assert.match(serviceWorker, /STATIC_ASSETS\.includes\(url\.pathname\)/)
  assert.doesNotMatch(serviceWorker, /\/api\//)
  assert.doesNotMatch(notifications, /socket\.io|XTransformPort|authenticate/)
  assert.match(notifications, /visibilitychange/)
  assert.match(config, /favicon\.ico/)
  assert.equal(existsSync(legacyService), false)
})

test('uses optimized public hero and preset avatar assets', () => {
  const home = readFileSync(new URL('../src/components/views/home-view.tsx', import.meta.url), 'utf8')
  const avatars = readFileSync(new URL('../src/lib/profile-avatars.ts', import.meta.url), 'utf8')
  const config = readFileSync(new URL('../next.config.ts', import.meta.url), 'utf8')
  assert.match(home, /ghyar-market-hero\.webp/)
  assert.doesNotMatch(home, /ghyar-market-hero\.png/)
  assert.match(config, /source: '\/ghyar-market-hero\.png', destination: '\/ghyar-market-hero\.webp'/)
  assert.match(config, /source: '\/favicon\.ico', destination: '\/ghyar-market-logo\.png'/)
  assert.match(avatars, /profile-avatars\/turbocharger\.webp/)
  assert.match(avatars, /profile-avatars\/(?:electric-car|classic-car|fuel-gauge-car)\.webp/)
  for (const asset of ['ghyar-market-hero.webp', 'profile-avatars/turbocharger.webp', 'profile-avatars/electric-car.webp', 'profile-avatars/classic-car.webp', 'profile-avatars/fuel-gauge-car.webp']) {
    assert.equal(existsSync(new URL(`../public/${asset}`, import.meta.url)), true, asset)
  }
  assert.equal(existsSync(new URL('../public/ghyar-market-logo.png', import.meta.url)), true, 'approved logo')
})

test('keeps the intentionally removed saved-car feature out of application surfaces', () => {
  const types = readFileSync(new URL('../src/lib/ai/types.ts', import.meta.url), 'utf8')
  const tools = readFileSync(new URL('../src/lib/ai/tools.ts', import.meta.url), 'utf8')
  const planner = readFileSync(new URL('../src/lib/ai/planner.ts', import.meta.url), 'utf8')
  const deterministic = readFileSync(new URL('../src/lib/ai/deterministic.ts', import.meta.url), 'utf8')
  const nav = readFileSync(new URL('../src/components/mobile-bottom-nav.tsx', import.meta.url), 'utf8')
  const shell = readFileSync(new URL('../src/components/app-shell.tsx', import.meta.url), 'utf8')

  for (const source of [types, tools, planner, deterministic, nav, shell]) {
    assert.doesNotMatch(source, /car_create|userCar|user-cars|account\/cars|selectedCar|viewerFitment/)
  }
  assert.equal(existsSync(new URL('../src/components/views/my-cars-view.tsx', import.meta.url)), false)
  assert.equal(existsSync(new URL('../src/app/api/user-cars/route.ts', import.meta.url)), false)
})

test('keeps seller offer entry focused while retaining admin editing controls', () => {
  const seller = readFileSync(new URL('../src/components/views/shop-dashboard-view.tsx', import.meta.url), 'utf8')
  const admin = readFileSync(new URL('../src/components/admin-edit-dialog.tsx', import.meta.url), 'utf8')
  assert.doesNotMatch(seller, /OEM رقم|أسماء بحث إضافية|رقم القطعة/)
  assert.match(admin, /admin-part-number/)
  assert.match(admin, /admin-part-oem/)
  assert.match(admin, /admin-part-aliases/)
  assert.match(admin, /compatibilities/)
})

test('authorizes private images from resource participants instead of filenames', () => {
  const route = readFileSync(new URL('../src/app/api/private-image/route.ts', import.meta.url), 'utf8')
  const chat = readFileSync(new URL('../src/app/api/chat/route.ts', import.meta.url), 'utf8')
  const disputes = readFileSync(new URL('../src/app/api/disputes/route.ts', import.meta.url), 'utf8')
  const verification = readFileSync(new URL('../src/app/api/seller-verification/route.ts', import.meta.url), 'utf8')
  assert.match(route, /chatMessage\.findFirst/)
  assert.match(route, /productMessage\.findFirst/)
  assert.match(route, /dispute\.findFirst/)
  assert.match(route, /sellerVerification\.findFirst/)
  assert.match(route, /aIMessage\.findFirst/)
  assert.match(route, /const privateUrl =/)
  assert.match(route, /SAFE_PATH = .*\{20,220\}/)
  assert.match(route, /canAccessPrivateImage\(session/)
  assert.doesNotMatch(route, /path\.includes\(`-\$\{session\.id\}-`\)/)
  assert.match(chat, /isPrivateImageOwnedBy\(submittedImageUrl, 'chat', session\.id\)/)
  assert.match(disputes, /isPrivateImageOwnedBy\(url, 'evidence', session\.id\)/)
  assert.match(verification, /isPrivateImageOwnedBy\(url, 'verification', session\.id\)/)
})