import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Phase 1 requires MFA for administrators and fresh step-up for privileged writes', () => {
  const auth = read('src/lib/auth.ts')
  const loginPolicy = read('src/lib/login-policy.ts')
  const adminMfa = read('src/lib/admin-mfa.ts')
  const users = read('src/app/api/admin/users/route.ts')
  const stores = read('src/app/api/admin/stores/route.ts')
  const parts = read('src/app/api/parts/route.ts')
  const adminParts = read('src/app/api/admin/parts/route.ts')
  const verification = read('src/app/api/seller-verification/route.ts')
  const disputes = read('src/app/api/disputes/route.ts')
  const reports = read('src/app/api/reports/route.ts')
  const reviews = read('src/app/api/reviews/route.ts')
  const aiActions = read('src/app/api/ai/actions/route.ts')
  assert.match(auth, /ADMIN_MFA_REQUIRED/)
  assert.match(auth, /requireAdminStepUp/)
  assert.match(auth, /ADMIN_STEP_UP_TTL_MS/)
  assert.doesNotMatch(loginPolicy, /role\s*!==\s*['"]ADMIN['"]/)
  assert.match(adminMfa, /TOTP_DIGITS = 6/)
  assert.match(adminMfa, /generateRecoveryCodes/)
  assert.match(adminMfa, /aes-256-gcm/)
  assert.match(adminMfa, /adminMfaLastCounter/)
  for (const source of [users, stores, adminParts, verification, disputes, reports, reviews, aiActions]) assert.match(source, /requireAdminStepUp/)
  assert.ok((parts.match(/requireAdminStepUp\(\)/g) || []).length >= 2)
})

test('Phase 1 binds seller verification to identity and explicit moderation state', () => {
  const schema = read('prisma/schema.prisma')
  const migration = read('prisma/phase1-security-trust-20260906.sql')
  const sellerStore = read('src/app/api/shop/store/route.ts')
  const verification = read('src/app/api/seller-verification/route.ts')
  const publicMarket = read('src/lib/public-marketplace.ts')
  assert.match(schema, /verifiedBusinessName/)
  assert.match(schema, /verifiedPhone/)
  assert.match(schema, /verifiedAddress/)
  assert.match(schema, /moderationStatus/)
  assert.match(migration, /CHANGES_PENDING/)
  assert.match(migration, /ProductReview_userId_partId_key/)
  assert.match(migration, /StoreReview_userId_storeId_key/)
  assert.match(sellerStore, /CHANGES_PENDING/)
  assert.match(verification, /updateMany[\s\S]*status:\s*'PENDING'/)
  assert.match(publicMarket, /moderationStatus/)
})

test('Phase 1 verifies new emails and strengthens login verification codes', () => {
  const loginVerification = read('src/lib/login-verification.ts')
  const emailChange = read('src/lib/email-change.ts')
  const emailVerify = read('src/app/api/account/email/verify/route.ts')
  const account = read('src/app/api/account/route.ts')
  const register = read('src/app/api/auth/register/route.ts')
  assert.match(loginVerification, /randomInt\(100000, 1000000\)/)
  assert.match(loginVerification, /LOGIN_CODE_MAX_ATTEMPTS\s*=\s*5/)
  assert.match(emailChange, /randomInt\(100000, 1000000\)/)
  assert.match(emailChange, /EMAIL_CHANGE_MAX_ATTEMPTS\s*=\s*5/)
  assert.match(emailVerify, /sessionVersion:\s*\{ increment: 1 \}/)
  assert.match(account, /issueEmailChange/)
  assert.doesNotMatch(register, /db\.user\.delete\(/)
})

test('Phase 1 only accepts media from the exact Ghyar Market Supabase project', () => {
  const config = read('next.config.ts')
  const proxy = read('src/proxy.ts')
  const storageUrl = read('src/lib/storage-url.ts')
  const parts = read('src/app/api/parts/route.ts')
  const adminParts = read('src/app/api/admin/parts/route.ts')
  assert.match(config, /sufrsfrrrzhhdluolxdf\.supabase\.co/)
  assert.match(proxy, /sufrsfrrrzhhdluolxdf\.supabase\.co/)
  assert.doesNotMatch(config, /\*\.supabase\.co/)
  assert.doesNotMatch(proxy, /\*\.supabase\.co/)
  assert.match(storageUrl, /url\.origin !== supabaseOrigin\(\)/)
  assert.match(storageUrl, /EXPECTED_SUPABASE_ORIGIN/)
  assert.match(parts, /isPublicUploadUrl/)
  assert.match(adminParts, /isPublicUploadUrl/)
})

test('Phase 1 invoice HTML is private, non-cacheable and contains no executable script', () => {
  const invoice = read('src/app/api/invoices/route.ts')
  assert.match(invoice, /private, no-store, max-age=0/)
  assert.match(invoice, /default-src 'none'/)
  assert.match(invoice, /script-src 'none'/)
  assert.match(invoice, /frame-ancestors 'none'/)
  assert.match(invoice, /Referrer-Policy': 'no-referrer'/)
  assert.doesNotMatch(invoice, /onclick=/)
  assert.doesNotMatch(invoice, /window\.print/)
})

test('Phase 1 critical moderation mutations are audited', () => {
  const sources = ['src/app/api/admin/users/route.ts','src/app/api/admin/stores/route.ts','src/app/api/admin/parts/route.ts','src/app/api/reviews/route.ts','src/app/api/reports/route.ts','src/app/api/disputes/route.ts','src/app/api/seller-verification/route.ts'].map(read)
  for (const source of sources) assert.match(source, /audit\(/)
})
