import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getSession, hashPassword, verifyPassword, createSession, requireAdminStepUp } from '@/lib/auth'
import { deleteUploadedFiles } from '@/lib/storage'
import { isProfileAvatar } from '@/lib/profile-avatars'
import { normalizeEgyptianMobile } from '@/lib/egyptian-phone'
import { audit } from '@/lib/audit'
import { recipientEmailError, validateRecipientEmail } from '@/lib/email-deliverability'
import { isPublicUploadUrl } from '@/lib/storage-url'
import { issueEmailChange } from '@/lib/email-change'
import { isBreachedPassword } from '@/lib/breached-password'
import { queueAccountSecurityNotice } from '@/lib/security-notifications'

function emailHint(email:string){const[local,domain]=email.split('@');return`${local.slice(0,2)}${'*'.repeat(Math.max(2,local.length-2))}@${domain}`}
export async function PUT(req:NextRequest){try{const session=await getSession();if(!session)return NextResponse.json({error:'غير مصرح'},{status:401});const body=await req.json();const name=typeof body.name==='string'?body.name.trim():session.name;const emailValidation=validateRecipientEmail(typeof body.email==='string'?body.email:session.email);const requestedEmail=emailValidation.email;const phoneInput=typeof body.phone==='string'?body.phone.trim():session.phone||'';const phone=phoneInput?normalizeEgyptianMobile(phoneInput):null;const currentPassword=typeof body.currentPassword==='string'?body.currentPassword:'';const newPassword=typeof body.newPassword==='string'?body.newPassword:'';const emailNotifications=typeof body.emailNotifications==='boolean'?body.emailNotifications:session.emailNotifications??true;const avatar=body.avatar===null||body.avatar===''?null:isProfileAvatar(body.avatar)||isPublicUploadUrl(body.avatar)?body.avatar:session.avatar||null
if(name.length<2||name.length>100)return NextResponse.json({error:'الاسم يجب أن يكون بين حرفين و100 حرف'},{status:400});if(!emailValidation.valid)return NextResponse.json({error:recipientEmailError(emailValidation),suggestion:emailValidation.suggestion},{status:400});if(phoneInput&&!phone)return NextResponse.json({error:'رقم الموبايل المصري غير صالح'},{status:400});if(newPassword&&(newPassword.length<8||newPassword.length>128))return NextResponse.json({error:'كلمة المرور الجديدة يجب أن تكون بين 8 و128 حرفاً'},{status:400});if(newPassword&&await isBreachedPassword(newPassword))return NextResponse.json({error:'كلمة المرور ظهرت في تسريبات معروفة. اختر كلمة مرور مختلفة وطويلة.'},{status:400})
const user=await db.user.findUnique({where:{id:session.id}});if(!user)return NextResponse.json({error:'الحساب غير موجود'},{status:404});const emailChanged=requestedEmail!==user.email;if(emailChanged||newPassword){if(!currentPassword||!(await verifyPassword(currentPassword,user.password)))return NextResponse.json({error:'كلمة المرور الحالية غير صحيحة'},{status:400})}if(emailChanged){if(session.role==='ADMIN')await requireAdminStepUp();const existing=await db.user.findUnique({where:{email:requestedEmail},select:{id:true}});if(existing&&existing.id!==user.id)return NextResponse.json({error:'البريد الإلكتروني مستخدم بالفعل'},{status:409})}
const updated=await db.user.update({where:{id:session.id},data:{name,phone,avatar,emailNotifications,...(newPassword?{password:await hashPassword(newPassword),sessionVersion:{increment:1}}:{})}});if(avatar!==user.avatar)await deleteUploadedFiles([user.avatar]);if(newPassword){await audit({actorId:session.id,action:'ACCOUNT_PASSWORD_CHANGED',targetType:'user',targetId:session.id});await queueAccountSecurityNotice({userId:session.id,email:user.email,name:updated.name,event:'تم تغيير كلمة المرور',message:'تم تغيير كلمة مرور حسابك في غيار ماركت.'}).catch(()=>false)}let emailChange:Awaited<ReturnType<typeof issueEmailChange>>|null=null;if(emailChanged)emailChange=await issueEmailChange({userId:user.id,name:updated.name,oldEmail:user.email,targetEmail:requestedEmail});await createSession({id:updated.id,name:updated.name,email:updated.email,role:updated.role as 'BUYER'|'ADMIN'|'SHOP_OWNER',phone:updated.phone,avatar:updated.avatar,emailNotifications:updated.emailNotifications,emailDeliveryStatus:updated.emailDeliveryStatus,emailDeliveryReason:updated.emailDeliveryReason,emailDeliveryAt:updated.emailDeliveryAt,sessionVersion:updated.sessionVersion,mfaVerifiedAt:session.mfaVerifiedAt},req,session.sessionId);return NextResponse.json({user:{id:updated.id,name:updated.name,email:updated.email,role:updated.role,phone:updated.phone,avatar:updated.avatar,emailNotifications:updated.emailNotifications,emailDeliveryStatus:updated.emailDeliveryStatus,emailDeliveryReason:updated.emailDeliveryReason,emailDeliveryAt:updated.emailDeliveryAt},...(emailChange?{emailChangeVerificationRequired:true,challengeId:emailChange.id,emailHint:emailHint(emailChange.targetEmail),expiresIn:600}:{})})}catch(error){if(error instanceof Error&&error.message==='STEP_UP_REQUIRED')return NextResponse.json({error:'يلزم تأكيد هوية المدير من صفحة أمان المدير قبل تغيير البريد الإلكتروني.',stepUpUrl:'/admin/security'},{status:428});if(error instanceof Error&&(error.message==='EMAIL_NOT_CONFIGURED'||error.message==='EMAIL_DELIVERY_FAILED'))return NextResponse.json({error:'تم حفظ باقي التغييرات، لكن تعذر إرسال رمز تأكيد البريد الجديد. حاول مرة أخرى لاحقاً.'},{status:503});console.error('Account update failed',error);return NextResponse.json({error:'تعذر تحديث الحساب'},{status:500})}}
