'use client'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Copy, KeyRound, ShieldCheck } from 'lucide-react'
type Enrollment = { enrollmentId: string; secret: string; otpauthUri: string; account: string }
export function MfaManagement() {
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null); const [code, setCode] = useState(''); const [recoveryCodes, setRecoveryCodes] = useState<string[] | null>(null); const [enabled, setEnabled] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void fetch('/api/account/mfa/setup', { cache: 'no-store' }).then((response) => response.json()).then((data) => setEnabled(Boolean(data.enabled))).catch(() => setError('تعذر تحميل حالة المصادقة')) }, [])
  const start = async () => { setLoading(true); setError(''); try { const response = await fetch('/api/account/mfa/setup', { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'تعذر بدء الإعداد'); setEnrollment(data); setCode('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر بدء الإعداد') } finally { setLoading(false) } }
  const confirm = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch('/api/auth/admin-mfa/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enrollmentId: enrollment?.enrollmentId, code }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'رمز غير صحيح'); setEnrollment(null); setCode(''); setRecoveryCodes(data.recoveryCodes || []); setEnabled(true); setMessage('تم تفعيل المصادقة متعددة العوامل.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر التفعيل') } finally { setLoading(false) } }
  const disable = async () => { setLoading(true); setError(''); try { const response = await fetch('/api/account/mfa/disable', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'رمز غير صحيح'); setCode(''); setEnabled(false); setMessage('تم إيقاف المصادقة متعددة العوامل.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر الإيقاف') } finally { setLoading(false) } }
  const copy = (value: string) => { void navigator.clipboard?.writeText(value) }
  return <Card className="market-card"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5" />المصادقة متعددة العوامل</CardTitle><CardDescription>ميزة اختيارية تضيف رمزاً من تطبيق المصادقة عند تسجيل الدخول.</CardDescription></CardHeader><CardContent className="space-y-4">{recoveryCodes ? <div className="space-y-3"><p className="text-sm font-medium">احفظ رموز الاسترداد الآن. تظهر مرة واحدة فقط.</p><div dir="ltr" className="grid gap-2 rounded-xl border bg-muted/30 p-3 font-mono text-sm">{recoveryCodes.map((item) => <button type="button" key={item} onClick={() => copy(item)} className="text-left hover:text-primary">{item}</button>)}</div><Button variant="outline" onClick={() => setRecoveryCodes(null)}>حفظت الرموز</Button></div> : enrollment ? <form onSubmit={confirm} className="space-y-4"><p className="text-sm">أضف الحساب إلى Google Authenticator أو Microsoft Authenticator، ثم أدخل الرمز الحالي.</p><div className="space-y-2"><Label>المفتاح اليدوي</Label><div className="flex gap-2"><Input readOnly dir="ltr" value={enrollment.secret} /><Button type="button" variant="outline" size="icon" onClick={() => copy(enrollment.secret)}><Copy className="size-4" /></Button></div></div><div className="space-y-2"><Label>رمز التطبيق</Label><Input autoFocus autoComplete="one-time-code" inputMode="numeric" dir="ltr" value={code} onChange={(event) => setCode(event.target.value)} placeholder="123456" /></div><Button disabled={loading || !/^\d{6}$/.test(code)}><KeyRound className="ml-2 size-4" />تفعيل المصادقة</Button></form> : enabled ? <div className="space-y-3"><p className="text-sm text-emerald-700 dark:text-emerald-300">المصادقة مفعلة على هذا الحساب.</p><Label>لإيقافها، أدخل رمز التطبيق الحالي</Label><div className="flex gap-2"><Input autoComplete="one-time-code" inputMode="numeric" dir="ltr" value={code} onChange={(event) => setCode(event.target.value)} placeholder="123456" /><Button variant="destructive" onClick={() => void disable()} disabled={loading || !code.trim()}>إيقاف</Button></div></div> : <Button onClick={() => void start()} disabled={loading}><ShieldCheck className="ml-2 size-4" />تفعيل المصادقة</Button>}{message && <p className="text-sm text-emerald-700 dark:text-emerald-300">{message}</p>}{error && <p className="text-sm text-destructive">{error}</p>}</CardContent></Card>
}
