import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { requireAdminStepUp, requireAuth } from '@/lib/auth'
import { createNotification } from '@/lib/notifications'
import { audit } from '@/lib/audit'
import { isPrivateImageOwnedBy } from '@/lib/private-image'
import { decodeCursor, encodeCursor, keysetBefore, parseLimit } from '@/lib/pagination'

const EVIDENCE_URL=/^\/api\/private-image\?path=[A-Za-z0-9%._-]+$/; const PRIVATE_HEADERS={'Cache-Control':'private, no-store, max-age=0'}
export async function GET(req:NextRequest){try{const session=await requireAuth();const url=new URL(req.url);const admin=session.role==='ADMIN'&&url.searchParams.get('scope')==='admin';const id=url.searchParams.get('id')?.trim();if(id){const dispute=await db.dispute.findFirst({where:{id,...(admin?{}:{buyerId:session.id})},include:{order:{include:{part:{select:{name:true}},store:{select:{name:true}}}},buyer:{select:{name:true,email:admin}},reviewedBy:{select:{name:true}}}});return dispute?NextResponse.json({dispute},{headers:PRIVATE_HEADERS}):NextResponse.json({error:'النزاع غير موجود'},{status:404,headers:PRIVATE_HEADERS})}const limit=parseLimit(url.searchParams.get('limit'),25,100);const cursor=decodeCursor(url.searchParams.get('cursor'));const where:any=admin?{}:{buyerId:session.id};const before=keysetBefore(cursor);if(before)where.AND=[before];const rows=await db.dispute.findMany({where,select:{id:true,type:true,status:true,reason:true,createdAt:true,orderId:true,order:{select:{part:{select:{name:true}},store:{select:{name:true}}}},buyer:admin?{select:{name:true}}:false},orderBy:[{createdAt:'desc'},{id:'desc'}],take:limit+1});const disputes=rows.slice(0,limit);return NextResponse.json({disputes,nextCursor:rows.length>limit&&disputes.length?encodeCursor(disputes[disputes.length-1]):null},{headers:PRIVATE_HEADERS})}catch(error){const message=error instanceof Error?error.message:'';return NextResponse.json({error:message==='UNAUTHORIZED'?'غير مصرح':'تعذر تحميل النزاعات'},{status:message==='UNAUTHORIZED'?401:500,headers:PRIVATE_HEADERS})}}
export async function POST(req:NextRequest){try{const session=await requireAuth();const{orderId,type,reason,evidenceUrls}=await req.json();const order=await db.order.findFirst({where:{id:orderId,buyerId:session.id,status:{in:['SHIPPED','DELIVERED']}},select:{id:true,storeId:true,store:{select:{ownerId:true}}}});if(!order)return NextResponse.json({error:'الطلب غير موجود أو غير مؤهل لفتح نزاع'},{status:404});if(!['RETURN','WRONG_ITEM','DAMAGED','DELIVERY','OTHER'].includes(type)||typeof reason!=='string'||reason.trim().length<10||reason.length>2000)return NextResponse.json({error:'اكتب سببًا واضحًا للنزاع'},{status:400});const urls=Array.isArray(evidenceUrls)?evidenceUrls.filter((url):url is string=>typeof url==='string'&&EVIDENCE_URL.test(url)&&isPrivateImageOwnedBy(url,'evidence',session.id)).slice(0,3):[];const dispute=await db.dispute.create({data:{orderId,buyerId:session.id,storeId:order.storeId,type,reason:reason.trim(),evidenceUrls:urls.length?JSON.stringify(urls):null}});await Promise.allSettled([createNotification({userId:order.store.ownerId,title:'نزاع جديد على طلب',message:'فتح العميل طلب حماية جديد. راجع تفاصيل الطلب.',type:'DISPUTE',link:'shop-dashboard',dedupeKey:`dispute-opened/${dispute.id}/${order.store.ownerId}`}),audit({actorId:session.id,action:'DISPUTE_OPENED',targetType:'order',targetId:orderId})]);return NextResponse.json({dispute},{status:201})}catch(error){if((error as{code?:string}).code==='P2002')return NextResponse.json({error:'يوجد نزاع مفتوح لهذا الطلب بالفعل'},{status:409});const message=error instanceof Error?error.message:'';return NextResponse.json({error:message==='UNAUTHORIZED'?'غير مصرح':'تعذر فتح النزاع'},{status:message==='UNAUTHORIZED'?401:500})}}
export async function PUT(req:NextRequest){try{const admin=await requireAdminStepUp();const{id,status,resolution}=await req.json();if(!['RESOLVED_BUYER','RESOLVED_SELLER','REJECTED'].includes(status)||typeof resolution!=='string'||resolution.trim().length<3)return NextResponse.json({error:'قرار الإدارة غير صالح'},{status:400});const dispute=await db.$transaction(async(tx)=>{const current=await tx.dispute.findUnique({where:{id},include:{order:{include:{items:true}}}});if(!current)throw new Error('NOT_FOUND');const claimed=await tx.dispute.updateMany({where:{id,status:'OPEN'},data:{status,resolution:resolution.trim().slice(0,2000),reviewedById:admin.id}});if(claimed.count!==1)throw new Error('DISPUTE_CHANGED');if(status==='RESOLVED_BUYER'&&current.order.status!=='RETURNED'){const claimedOrder=await tx.order.updateMany({where:{id:current.orderId,status:current.order.status},data:{status:'RETURNED',paymentStatus:current.order.paymentStatus==='PAID'?'REFUNDED':current.order.paymentStatus}});if(claimedOrder.count!==1)throw new Error('DISPUTE_CHANGED');await tx.orderTimeline.create({data:{orderId:current.orderId,status:'RETURNED',note:'تم قبول طلب الحماية والاسترجاع بقرار الإدارة'}});if(current.order.items.length){for(const item of current.order.items)if(item.partId)await tx.part.updateMany({where:{id:item.partId},data:{stock:{increment:item.quantity}}})}else await tx.part.update({where:{id:current.order.partId},data:{stock:{increment:current.order.quantity}}});if(current.order.couponCode)await tx.coupon.updateMany({where:{code:current.order.couponCode,usedCount:{gt:0}},data:{usedCount:{decrement:1}}})}return tx.dispute.findUniqueOrThrow({where:{id}})});await Promise.allSettled([createNotification({userId:dispute.buyerId,title:'صدر قرار في النزاع',message:resolution.trim(),type:'DISPUTE',link:'orders',dedupeKey:`dispute-resolved/${dispute.id}/${dispute.buyerId}`}),audit({actorId:admin.id,action:'DISPUTE_RESOLVED',targetType:'dispute',targetId:id,metadata:{status,resolution:resolution.trim().slice(0,500)}})]);return NextResponse.json({dispute})}catch(error){const message=error instanceof Error?error.message:'';if(message==='STEP_UP_REQUIRED')return NextResponse.json({error:'يلزم تأكيد هوية المدير قبل حسم النزاع.',stepUpUrl:'/admin/security'},{status:428});if(message==='DISPUTE_CHANGED')return NextResponse.json({error:'تم حسم النزاع من جلسة أخرى. أعد تحميل الصفحة.'},{status:409});return NextResponse.json({error:message==='UNAUTHORIZED'||message==='FORBIDDEN'?'غير مصرح':'تعذر حفظ القرار'},{status:message==='UNAUTHORIZED'||message==='FORBIDDEN'?403:500})}}
